/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CompContent: typeof import('./src/components/CompContent.vue')['default']
    CompFooter: typeof import('./src/components/CompFooter.vue')['default']
    CompHeader: typeof import('./src/components/CompHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
  }
}
